version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_path = "requirements.txt"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 121
  skip_doc_coverage = ["module", "magic", "init", "class", "nonpublic"]

[[transformers]]
name = "autopep8"
enabled = true